CREATE TABLE IF NOT EXISTS user_details (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(250) NOT NULL,
    city VARCHAR(250) NOT NULL,
    email VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS summa (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(250) NOT NULL,
    city VARCHAR(250) NOT NULL,
    email VARCHAR(250)
);