name: Deploy to Nexus

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install
      
    - name: Use `sed` to replace text
      run: |
        # Replace 'foo' with 'bar' in example.txt
        sed  's/NEXUS_USERNAME/admin/g' .github/settings.xml
        sed  's/NEXUS_PASSWORD/admin@123/g' .github/settings.xml
        
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .github/settings.xml
        git commit -m 'Updated settings.xml with sed'
        git push
  
    - name: Deploy to Nexus
      run: mvn deploy --settings .github/settings.xml
